Effect of marriage on the efficacy of interventions designed to increase mammography screening

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(car)
library(table1)
library(kableExtra)
library(ggplot2)
library(gmodels)
library(lmtest)
library(generalhoslem)
library(DescTools)
library(VGAM)
library(readr)
library(car)
```

```{r}
mamm_data <- read.csv("BIOSTAT651_mammography_data.csv")
str(mamm_data)

# first column is redundant
# removing the first column
mamm_data <- mamm_data[, 2: 13]

# making the variables factors and ordered when necessary
mamm_data <- mamm_data %>%
               mutate(treatment = factor(treatment, ordered = FALSE),
                      resp6 = factor(resp6, ordered = TRUE),
                      stagefwup = factor(stagefwup, levels = c("1", "2", "3"), ordered = TRUE),
                      educmorethanHSdegree = factor(educmorethanHSdegree, ordered = FALSE),
                      inclt15k = factor(inclt15k, ordered = FALSE),
                      workpay = factor(workpay, ordered = FALSE),
                      married = factor(married, ordered = FALSE),
                      stagebase = factor(stagebase, levels = c("1", "2"), ordered = TRUE),
                      docnursespoken2years = factor(docnursespoken2years, ordered = FALSE),
                      fdrhistory = factor(fdrhistory, ordered = FALSE)) %>%
  
               mutate(treatment = case_when(
                      treatment == 0 ~ "Control",
                      treatment == 1 ~ "Phone",
                      treatment == 2 ~ "Mail",
                      treatment == 3 ~ "Phone and mail")) %>%
               mutate(resp6 = case_when(
                      resp6 == 0 ~ "Didn't screen",
                      resp6 == 1 ~ "Screened")) %>%
               mutate(stagefwup = case_when(
                      stagefwup == 1 ~ "Precontemplation",
                      stagefwup == 2 ~ "Contemplation",
                      stagefwup == 3 ~ "Action")) %>%
               mutate(educmorethanHSdegree = case_when(
                      educmorethanHSdegree == 0 ~ "Low education",
                      educmorethanHSdegree == 1 ~ "High education")) %>%
               mutate(inclt15k = case_when(
                      inclt15k == 0 ~ "High income",
                      inclt15k == 1 ~ "Low income")) %>%
               mutate(workpay = case_when(
                      workpay == 0 ~ "Not working",
                      workpay == 1 ~ "Working")) %>%
               mutate(married = case_when(
                      married == 0 ~ "Unmarried",
                      married == 1 ~ "Married")) %>%
               mutate(stagebase = case_when(
                      stagebase == 1 ~ "Precontemplation",
                      stagebase == 2 ~ "Contemplation")) %>%
               mutate(docnursespoken2years = case_when(
                      docnursespoken2years == 0 ~ "Wasn't recommended",
                      docnursespoken2years == 1 ~ "Recommended")) %>%
               mutate(fdrhistory = case_when(
                      fdrhistory == 0 ~ "No family history",
                      fdrhistory == 1 ~ "Family history"))

# setting reference levels for categorical variables
mamm_data$treatment <- relevel(as.factor(mamm_data$treatment), ref = "Control")
mamm_data$stagefwup <- relevel(as.factor(mamm_data$stagefwup), ref = "Precontemplation")
mamm_data$stagebase <- relevel(as.factor(mamm_data$stagebase), ref = "Precontemplation")

# labelling variables for the demographics table
label(mamm_data$age) <- "Age ᵃ" 
label(mamm_data$treatment) <- "Treatment" 
label(mamm_data$resp6) <- "6-month mammography"
label(mamm_data$educmorethanHSdegree) <- " Education" 
label(mamm_data$inclt15k) <- "Income"
label(mamm_data$workpay) <- "Workpay" 
label(mamm_data$married) <- "Married"
label(mamm_data$docnursespoken2years) <- "Mammogram recommendation in the last year or two" 
label(mamm_data$fdrhistory) <- "Family history"
label(mamm_data$stagebase) <- "Baseline stage of mammography" 
label(mamm_data$stagefwup) <- "Follow-up stage of mammography"
fn <- "ᵃ Numeric variable"

# creating a demographics table of all the variables
(demographics <- table1(~ age + treatment + resp6 + educmorethanHSdegree + inclt15k + workpay + married + docnursespoken2years + fdrhistory + stagebase + stagefwup, data = mamm_data, footnote = fn))

# exploratory data analysis

# looking at the continuous variable with both the outcomes
# age and resp6
mamm_data %>%
  group_by(resp6) %>% 
  summarize(n = n(),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE)) %>% 
  ggplot(aes(x = resp6, y = mean)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  geom_errorbar(aes(x = resp6, ymin = mean - sd, ymax = mean + sd), width = 0.5, linewidth = 0.75) +
  geom_text(aes(y = 5, label = n)) +
  labs(y = "Age (years)", x = "Compliance")

# age and stagefwup
mamm_data %>%
  group_by(stagefwup) %>% 
  summarize(n = n(),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE)) %>% 
  ggplot(aes(x = stagefwup, y = mean)) +
  geom_bar(stat = "identity", color = "black", fill = "lightblue") +
  geom_errorbar(aes(x = stagefwup, ymin = mean - sd, ymax = mean + sd), width = 0.5, linewidth = 0.75) +
  geom_text(aes(y = 5, label = n)) +
  labs(y = "Age (years)", x = "Cognitive stage")

# age, resp6, and stagefwup
mamm_data %>% 
  group_by(stagefwup, resp6) %>% 
  summarize(n = n(),
            mean = mean(age, na.rm = TRUE),
            sd = sd(age, na.rm = TRUE)) %>% 
  ggplot(aes(x = stagefwup, y = mean, fill = resp6)) +
  geom_bar(stat = "identity", position = "dodge") +
  geom_errorbar(aes(ymin = mean - sd, ymax = mean + sd), width = 0.5, linewidth = 0.75, position = position_dodge(0.9)) +
  geom_text(aes(y = 5, label = n), position = position_dodge(0.9)) +
  labs(y = "Age (years)", x = "Cognitive stage", fill = "Compliance")

# looking at the main explanatory variable with both the outcomes
# resp6, stagefwup, treatment
resp6_colors <- c("Screened" = "gold", "Didn't screen" = "violet")
stagefwup_colors <- c("Action" = "darkgreen", "Contemplation" = "darkblue", "Precontemplation" = "darkred")

ggplot(data = mamm_data, aes(x = treatment, fill = factor(stagefwup), color = factor(resp6))) +
  geom_bar(position = "stack", width = 0.7, stat = "count") +  
  theme_minimal() +
  labs(
    title = "Compliance and cognitive stage by treatment",
    ylab = "Count"
  ) +
  scale_fill_manual(name = "Cognitive stage", values = stagefwup_colors) +
  scale_color_manual(name = "Compliance", values = resp6_colors) 

# mosaicplot(table(mamm_data$resp6, mamm_data$stagefwup))
# treatment and resp6
# ggplot(data = mamm_data, aes(x = resp6, fill = factor(treatment))) +
# geom_bar() +
# theme_minimal() +
# labs(
#   title = "Bar Chart of Species Count",
#   ylab = "Count",
#   fill = "Species"
#  )
  
# treatment and stagefwup
# ggplot(data = mamm_data, aes(x = stagefwup, fill = factor(treatment))) +
# geom_bar() +
# theme_minimal() +
# labs(
#   title = "Bar Chart of Species Count",
#   ylab = "Count",
#   fill = "Species"
#  )
  
# numeric variables
# hist(mamm_data$age)

# looking at the correlation between the two outcomes
chisq.test(mamm_data$resp6, mamm_data$stagefwup, correct = FALSE)
# p-value is less than 0.05
# reject the null hypothesis
# the two outcomes are dependent

# looking at the missingness in the data
sum(complete.cases(mamm_data)) # 958 complete observations
(sum(complete.cases(mamm_data))/ nrow(mamm_data))* 100 # 91.93858% complete observations
# safe to remove observations with missing data

# centering age, the only numeric variable
mamm_data$age <- mamm_data$age - mean(mamm_data$age)

# finalising on the cleaned dataset
mamm_data <- mamm_data[complete.cases(mamm_data), ]
```

```{r}
# crosstable
# generalised logit model: log(\pi_ij/ \pi_i0) = \beta_0j + \beta_1j treatment
# \pi_ij = P(stagefwup_i = j| X_i)
CrossTable(mamm_data$treatment, mamm_data$resp6)

# full model contains all the variables and the interaction we want to test for
# we want to test for treatment and married
full_model1 <- glm(data = mamm_data, as.factor(resp6) ~ treatment + age + educmorethanHSdegree + workpay + docnursespoken2years + inclt15k + married + fdrhistory + stagebase + treatment* married, family = binomial(link = logit))
summary(full_model1)
# based on Wald test p-values:
# (i) age, married, treatment:married are significant at 0.05 significance level
# (ii) inclt15k is significant at 0.001 significance level
# (iii) the intercept, treatment, stagebase is significant at < 0.001 significance level

# educmorethanHSdegree, workpay are heavily correlated with inclt15k based on literature survey
# docnursespoken2years is heavily correlated with stagebase based on literature survey
# we test the same via chi-square tests for our dataset - results verify
chisq.test(mamm_data$educmorethanHSdegree, mamm_data$inclt15k, correct = FALSE)
chisq.test(mamm_data$workpay, mamm_data$inclt15k, correct = FALSE)
chisq.test(mamm_data$docnursespoken2years, mamm_data$stagebase, correct = FALSE)

# we test for educmorethanHSdegree, workpay, docnursespoken2years being significantly jointly
# testing the same via LRT and score tests
reduced_model1 <- glm(data = mamm_data, as.factor(resp6) ~ treatment + age + inclt15k + married + fdrhistory + stagebase + treatment* married, family = binomial(link = logit))
summary(reduced_model1)
# based on Wald test p-values:
# (i) age is significant at 0.1 significance level
# (ii) inclt15k are significant at 0.05 significance level
# (iii) the intercept, stagebase is significant at 0.001 significance level

intercept_model1 <- glm(data = mamm_data, as.factor(resp6) ~ 1, family = binomial(link = logit))
summary(intercept_model1)

# based on both LRT and score test
anova(reduced_model1, full_model1, test = "LRT")
anova(reduced_model1, full_model1, test = "Rao")
# educmorethanHSdegree, workpay, docnursespoken2years coefficients are 0
# p-value's are greater than 0.05
# we fail to reject the null hypothesis
# so we eliminate educmorethanHSdegree, workpay, docnursespoken2years from the full model to get our final model

# all 1 < V IF < 5, covariates are moderately correlated
# no serious multicollinearity problem
vif_values <- vif(reduced_model1, type = c("terms"))
vif_table <- t(data.frame(VIF = vif_values))
kable(vif_table, digits = 4)

coefficients1 <- as.data.frame(coef(reduced_model1))
confidence1 <- as.data.frame(confint(reduced_model1))
p_values1 <- as.data.frame(summary(reduced_model1)$coefficients[, 4])
variables1 <- c("Intercept", "Mail treatment", "Phone treatment", "Phone and mail treatment", "Age", "Low income", "Unmarried", "No family history", "Contemplation at base", "Mail treatment* unmarried", "Phone treatment* unmarried", "Phone and mail treatment* unmarried")
estimates1 <- cbind(variables1, coefficients1, confidence1, p_values1)
colnames(estimates1) <- c("Variables", "Coefficients", "Lower bound", "Upper bound", "Significance")

variable_order1 <- estimates1$Variables
# Convert Variables to factor with the desired order
estimates1$Variables <- factor(estimates1$Variables, levels = unique(variable_order1))

ggplot(estimates1, aes(x = Variables, y = Coefficients)) +
  geom_point(size = 1.5, color = "darkblue") +
  geom_errorbar(aes(ymin = `Lower bound`, ymax = `Upper bound`), width = 0.2, color = "darkblue") +
  geom_text(aes(label = paste0(round(Coefficients, 2), 
                              ifelse(Significance < 0.001, "***", 
                                     ifelse(Significance < 0.01, "**", 
                                            ifelse(Significance < 0.05, "*", 
                                                   ifelse(Significance < 0.1, ".", "")))))), vjust = -0.5, size = 3, color = "darkblue") +
  coord_flip() +
  labs(title = "Primary outcome: compliance (6-month mammography screening)", x = "Predictor variables", y = "Log odds of compliance") +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8),
        legend.title = element_blank())

# Hosmer-Lemeshow goodness of fit test
logitgof(as.factor(mamm_data$resp6), fitted(reduced_model1))
# null hypothesis is that the model fits the data well
# p > 0.05, fail to reject the null hypothesis
# thus, the logit model fits the data well

# Combine the results into a data frame
# results on dof, deviance, aic
# used to compare models
results1 <- bind_rows(data.frame(Model = "Intercept Model", DoF = intercept_model1$df.residual, Deviance = intercept_model1$deviance, AIC = intercept_model1$aic),
                     data.frame(Model = "Reduced Model", DoF = reduced_model1$df.residual, Deviance = reduced_model1$deviance, AIC = reduced_model1$aic),
                     data.frame(Model = "Full Model", DoF = full_model1$df.residual, Deviance = full_model1$deviance, AIC = full_model1$aic))
(results1 <- kable(results1, caption = "Model comparison", format = "markdown"))

PseudoR2(reduced_model1, which = c("CoxSnell","Nagelkerke","McFadden"))
```

```{r}
# crosstable
# generalised logit model: log(\pi_ij/ \pi_i0) = \beta_0j + \beta_1j treatment
# \pi_ij = P(stagefwup_i = j| X_i)
CrossTable(mamm_data$treatment, mamm_data$stagefwup)

full_model2 <- vglm(stagefwup ~ treatment + age + educmorethanHSdegree + workpay + docnursespoken2years + inclt15k + married + fdrhistory + stagebase + treatment* married, data = mamm_data, family = multinomial(refLevel = "Precontemplation"), model = TRUE)
summary(full_model2)
# based on Wald test p-values:
# (i) (Intercept):1 is significant at 0.05 significance level
# (ii) treatmentMail:1, age:2, workpayWorking:1 are is significant at 0.1 significance level
# (iii) stagebaseContemplation:1, stagebaseContemplation:2 are significant at 0.001 significance level

reduced_model2 <- vglm(stagefwup ~ treatment + age + inclt15k + married + fdrhistory + stagebase + treatment* married, data = mamm_data, family = multinomial(refLevel = "Precontemplation"), model = TRUE)
summary(reduced_model2)

intercept_model2 <- vglm(stagefwup ~ 1, data = mamm_data, family = multinomial(refLevel = "Precontemplation"))
summary(intercept_model2)

coefficients2 <- as.data.frame(Coefficients(reduced_model2))
confidence2 <- as.data.frame(confint.default(reduced_model2))
stage_label <- as.data.frame(rep(c("Action", "Contemplation"), 12))
p_values2 <- as.data.frame(coefficients(summary(reduced_model2))[, 4])
variables2 <- c("Intercept", "Intercept", "Mail treatment", "Mail treatment", "Phone treatment", "Phone treatment", "Phone and mail treatment", "Phone and mail treatment", "Age", "Age", "Low income", "Low income", "Unmarried", "Unmarried", "No family history", "No family history", "Contemplation at base", "Contemplation at base", "Mail treatment* unmarried", "Mail treatment* unmarried", "Phone treatment* unmarried", "Phone treatment* unmarried", "Phone and mail treatment* unmarried", "Phone and mail treatment* unmarried")
estimates2 <- cbind(variables2, stage_label, coefficients2, confidence2, p_values2)
colnames(estimates2) <- c("Variables", "Follow up stage", "Coefficients", "Lower bound", "Upper bound", "Significance")

variable_order2 <- estimates2$Variables
# Convert Variables to factor with the desired order
estimates2$Variables <- factor(estimates2$Variables, levels = unique(variable_order2))

ggplot(estimates2, aes(x = Variables, y = Coefficients, color = `Follow up stage`)) +
  geom_point(size = 1.5) +
  geom_errorbar(aes(ymin = `Lower bound`, ymax = `Upper bound`), width = 0.2) +
  geom_text(aes(label = paste0(round(Coefficients, 2), 
                              ifelse(Significance < 0.001, "***", 
                                     ifelse(Significance < 0.01, "**", 
                                            ifelse(Significance < 0.05, "*", 
                                                   ifelse(Significance < 0.1, ".", ""))))), color = `Follow up stage`), vjust = -0.5, size = 3) +
  coord_flip() + 
  labs(title = "Secondary outcome: cognitive stage (follow-up of screening behaviour)", x = "Predictor variables", y = "Log odds of cognitive stage") +
  scale_color_manual(values = c("orange", "darkblue")) +
  theme_minimal() +
  theme(axis.text.y = element_text(size = 8), 
        legend.title = element_blank())

# Combine the results into a data frame
results2 <- bind_rows(data.frame(Model = "Intercept Model", DoF = df.residual_vlm(intercept_model2), Deviance = deviance(intercept_model2), Loglikelihood = logLik.vlm(intercept_model2), AIC = AIC(intercept_model2)),
                     data.frame(Model = "Reduced Model", DoF = df.residual_vlm(reduced_model2), Deviance = deviance(reduced_model2), Loglikelihood = logLik.vlm(reduced_model2), AIC = AIC(reduced_model2)),
                     data.frame(Model = "Full Model", DoF = df.residual_vlm(full_model2), Deviance = deviance(full_model2), Loglikelihood = logLik.vlm(full_model2), AIC = AIC(full_model2)))
(results2 <- kable(results2, caption = "Model comparison", format = "markdown"))

# Wald's test
waldtest(full_model2, reduced_model2)

# LRT
detach("package:lmtest", unload = TRUE)
lrtest(full_model2, reduced_model2)
# p value is more than 0.05
# fail to reject null - same for Wald's test
# educmorethanHSdegree + workpay + docnursespoken2years are simultaneously 0

mamm_data$stagefwup <- factor(mamm_data$stagefwup, levels = c("Precontemplation", "Contemplation", "Action"), ordered = TRUE)
prop_odds <- vglm(stagefwup ~ treatment + age + inclt15k + married + fdrhistory + stagebase + treatment* married, data = mamm_data, family = cumulative(link = "logitlink", parallel = TRUE))
summary(prop_odds) 

no_prop_odds <- vglm(stagefwup ~ treatment + age + inclt15k + married + fdrhistory + stagebase + treatment* married, data = mamm_data, family = cumulative(link = "logitlink", parallel = FALSE))
summary(no_prop_odds) 

lrtest(no_prop_odds, prop_odds)

# generalized Hosmer–Lemeshow
# compare observed with expected frequencies of the outcome
# test statistic distributed according to chi-squared distribution
# degrees of freedom depend upon the number of quantiles used and the number of outcome categories
logitgof(mamm_data$stagefwup, fitted(reduced_model2))
# more than 0.05
# fail to reject null
# good fit

# calculate the R-squared value
PseudoR2(reduced_model2, which = c("CoxSnell","Nagelkerke","McFadden"))
```
